name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

defaults:
  run:
    working-directory: giftway-ws

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: giftway-ws/package-lock.json

      - run: npm ci
      - run: npx nx sync:check
      - run: npx nx format:check --base="remotes/origin/main"
      - run: npx nx run-many -t lint typecheck test build
